model_path:
  model_local: "C:/Users/166565/Downloads/chat_app/models/mistral-7b-instruct-v0.1.Q5_K_M.gguf"  # downloaded from huggingface
model_type: "mistral_7b"
embeddings_model: "BAAI/bge-large-en-v1.5"
model_config:
  temperature: 0
  context_length: 4096
  gpu_layers: 0

chat_history_path: "./chat_sessions/"
